name: CI

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --no-cache-dir -r binder/requirements.txt
        python -m pip install --no-cache-dir -r book/requirements.txt

    - name: Build the book
      run: |
        jupyter-book build book/
